version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_rn
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/db-username
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB_FILE: /run/secrets/db-dbname
    volumes:
      - /home/RnMonitor_IPCA/data/pgdata:/var/lib/postgresql/data
    secrets:
      - db-username
      - db-password
      - db-dbname
    networks:
      - rnetwork
    restart: unless-stopped
  olap:
    container_name: mondrian_rn
    image: mondrianrn
    build:
      dockerfile: Dockerfile
      context: ./mondrian
    ports:
      - "8081:80"
    networks:
      - rnetwork
    restart: unless-stopped
  pdi:
    container_name: pdi_rn
    image: pdirn
    build:
      dockerfile: Dockerfile
      context: ./pdi
    networks:
      - rnetwork
    restart: unless-stopped
networks:
  rnetwork:
    driver: bridge
secrets:
  db-username:
    file: /home/RnMonitor_IPCA/secrets/DB_USERNAME
  db-password:
    file: /home/RnMonitor_IPCA/secrets/DB_PASSWORD
  db-dbname:
    file: /home/RnMonitor_IPCA/secrets/DB_DATABASE_NAME
