version: '3.1'

services:
  ${POSTGRES_SERVICE}:
    image: postgres:12-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - /home/RnMonitor_IPCA/data/pgdata:/var/lib/postgresql/data
    networks:
      - rnetwork
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
  olap:
    container_name: ${MONDRIAN_CONTAINER_NAME}
    image: mondrianrn
    build:
      dockerfile: Dockerfile
      context: ./mondrian
    ports:
      - ${OLAP_PORT}
    networks:
      - rnetwork
    restart: unless-stopped
  pdi:
    container_name: ${PDI_CONTAINER_NAME}
    image: pdirn
    build:
      dockerfile: Dockerfile
      context: ./pdi
    networks:
      - rnetwork
    restart: unless-stopped
networks:
  rnetwork:
    driver: bridge

